#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
    /config \
    /www \
    /downloads
  
chmod a+x \
  /aria2/script/*

chmod a+x \
  /aria2/ScriptCustom1/*

# set cron-restart-a2b
bash /aria2/script/cron-restart-a2b.sh
